<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/bootstrap.php';Auth::requireLogin(['technical','admin']);
if(is_post()){
    Csrf::verify();$id=(int)input('id');$action=(string)input('action');$reason=trim((string)input('reason'));
    $stmt=db()->prepare('SELECT id,status FROM registrations WHERE id=?');$stmt->execute([$id]);$reg=$stmt->fetch();if(!$reg){flash('error','Pendaftaran tidak ditemui.');redirect('pegawai_teknikal/pendaftaran.php');}
    if($action==='approve'){
        $check=db()->prepare("SELECT s.name,s.assistant_count,s.model_count,SUM(h.helper_type='assistant') actual_assistants,SUM(h.helper_type='model') actual_models FROM registrations r JOIN skills s ON s.id=r.skill_id LEFT JOIN registration_helpers h ON h.registration_id=r.id WHERE r.id=? GROUP BY r.id,s.id");
        $check->execute([$id]);$rules=$check->fetch();
        if(!$rules || (int)$rules['assistant_count']!==(int)$rules['actual_assistants'] || (int)$rules['model_count']!==(int)$rules['actual_models']){
            flash('error','Pendaftaran tidak mematuhi bilangan pembantu/model bagi bidang tersebut.');redirect('pegawai_teknikal/pendaftaran.php');
        }
        $stmt=db()->prepare("UPDATE registrations SET status='approved',approved_at=NOW(),approved_by=?,rejection_reason=NULL WHERE id=?");$stmt->execute([Auth::id(),$id]);audit(Auth::id(),'approve','registration',$id);flash('success','Pendaftaran diluluskan.');
    }
    elseif($action==='reject'){if($reason===''){flash('error','Sebab penolakan diperlukan.');redirect('pegawai_teknikal/pendaftaran.php');}$stmt=db()->prepare("UPDATE registrations SET status='rejected',rejection_reason=?,approved_at=NULL,approved_by=NULL WHERE id=?");$stmt->execute([$reason,$id]);audit(Auth::id(),'reject','registration',$id,['reason'=>$reason]);flash('success','Pendaftaran ditolak.');}
    redirect('pegawai_teknikal/pendaftaran.php');
}
$status=in_array($_GET['status']??'submitted',['submitted','approved','rejected'],true)?$_GET['status']:'submitted';$skillId=(int)($_GET['skill_id']??0);$skills=all_skills();$sql="SELECT r.*,s.name skill_name,z.name zone_name,u.full_name coach_name,GROUP_CONCAT(CONCAT(h.helper_type,': ',h.full_name) SEPARATOR '||') helpers FROM registrations r JOIN skills s ON s.id=r.skill_id JOIN zones z ON z.id=r.zone_id JOIN users u ON u.id=r.coach_user_id LEFT JOIN registration_helpers h ON h.registration_id=r.id WHERE r.status=?";$params=[$status];if($skillId){$sql.=' AND r.skill_id=?';$params[]=$skillId;}$sql.=' GROUP BY r.id ORDER BY s.sort_order,z.sort_order';$stmt=db()->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
$pageTitle='Semakan Pendaftaran';$activePage='technical';require BASE_PATH.'/partials/head.php';require BASE_PATH.'/partials/sidebar.php';require BASE_PATH.'/partials/flash.php';?>
<section class="dashboard-header"><div class="container text-center"><h1>Semakan Pendaftaran</h1><p>Sahkan peserta, pembantu dan model mengikut peraturan bidang.</p></div></section><section class="container py-4"><form method="get" class="card card-body mb-4"><div class="row g-3"><div class="col-md-5"><select name="status" class="form-select"><option value="submitted" <?= selected($status,'submitted') ?>>Menunggu</option><option value="approved" <?= selected($status,'approved') ?>>Diluluskan</option><option value="rejected" <?= selected($status,'rejected') ?>>Ditolak</option></select></div><div class="col-md-5"><select name="skill_id" class="form-select"><option value="0">Semua bidang</option><?php foreach($skills as $s):?><option value="<?= (int)$s['id'] ?>" <?= selected($skillId,$s['id']) ?>><?= e($s['name']) ?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Tapis</button></div></div></form><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Peserta</th><th>Zon/Bidang</th><th>Jurulatih</th><th>Pembantu/Model</th><th>Tindakan</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?= e($r['participant_name']) ?><br><small><?= e($r['institution']) ?></small></td><td><?= e($r['zone_name']) ?><br><small><?= e($r['skill_name']) ?></small></td><td><?= e($r['coach_name']) ?></td><td><?php foreach(array_filter(explode('||',(string)$r['helpers'])) as $h):?><div><?= e($h) ?></div><?php endforeach;?><?= !$r['helpers']?'<span class="text-muted">Tiada</span>':'' ?></td><td><?php if($r['status']==='submitted'):?><div class="d-grid gap-2"><form method="post"><?= Csrf::field() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="action" value="approve"><button class="btn btn-sm btn-success w-100">Lulus</button></form><form method="post" class="d-flex gap-1"><?= Csrf::field() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="action" value="reject"><input class="form-control form-control-sm" name="reason" placeholder="Sebab" required><button class="btn btn-sm btn-outline-danger">Tolak</button></form></div><?php else:?><span class="status status-<?= e($r['status']) ?>"><?= e(ucfirst($r['status'])) ?></span><?php if($r['rejection_reason']):?><small class="d-block text-danger"><?= e($r['rejection_reason']) ?></small><?php endif;?><?php endif;?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="text-center text-muted">Tiada rekod.</td></tr><?php endif;?></tbody></table></div></section><?php require BASE_PATH.'/partials/footer.php';?>
